# compressing the joint likehood calculation without an if expression...
# applies for-loop...
for p in patient_data:
    
# returns if statement...         
        joint_likelihood *= logistic_function(p.x) ** p.y * \
                                         (1.0 - logistic_function(p.x)) ** (1.0 - p.y)

# using logrithemic addition...
# value for joint_likelihood...
joint_likelihood = 0.0

# applies for-loop...
for p in patient_data:
    
# returns if statement...         
        joint_likelihood += math.log(logistic_function(p.x) ** p.y * \
                                         (1.0 - logistic_function(p.x)) ** (1.0 - p.y))

# define joint_likelihood is equal to the math.exp(joint_likelihood)...
joint_likelihood = math.exp(joint_likelihood)


# expressing a joint likelihood for logistic regression in sympy...
joint_likelihood = Sum(log((1.0 / (1.0 + exp( - (b + m * x(i)))))**y(i) * \
           (1.0 - 1.0 / (1.0 - (1.0 + exp( - (b + m * x(i))))))**(1-y(i))), (i, 0, n))
           