# this code show an InvalidParameterError...
# using a plain logistic regression in scipy...
# importing pandas as pd...
import pandas as pd

# importing LogisticRegression from sklearn.linear_model...
from sklearn.linear_model import LogisticRegression

# load the data...
# create the data set...
# https://bit.ly/33ebs2R...
# create the dataset...
data = {
    'x': [1, 2, 3, 4, 5],
    'y': [2, 4, 6, 8, 10]
}

# convert dataset into dataframe...
df = pd.DataFrame(data)

# extract input variables (all rows, all columns but last column)...
X = df.values[:, :-1]

# extract output column (all rows, last column)...
Y = df.values[:, -1]

# eerform logistic regression...
# turn off penalty...
model = LogisticRegression(penalty='none')

# fit model X and Y...
model.fit(X, Y)

# print beta1...
print(model.coef_.flatten())

# print beta0...
print(model.intercept_.flatten())

# this code shows an wrong type of an output...
# calculating the joint likelihood of observing all the points for a given logistic regression...
# importing math...
import math

# importing pandas as pd...
import pandas as pd

# create the dataset...
data = {
    'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'y': [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
}

# convert dataset inti dataframe...
df = pd.DataFrame(data)

# convert dataframe to tuples...
patient_data = df.itertuples()

# value of coefficient b0...
b0 = -3.17576395

# value of coefficient b1...
b1 = 0.69267212

# creating def function for x...
def logistic_function(x):
    
# formulate for p...    
    p = 1.0 / (1.0 + math.exp( - (b0 + b1 * x)))

# returns p...
    return p

# calculate the joint likelihood...
joint_likelihood = 1.0

# applies for-loop...
for p in patient_data:
    
# applied if-elif conditions...    
# applies if statement...    
    if p.y == 1.0:
        
# returns if statement...         
        joint_likelihood *= logistic_function(p.x)

# applies elif statement...                
    elif p.y == 0.0:
        
# returns elif statement...        
        joint_likelihood *= (1.0 - logistic_function(p.x))

# prints joint_likelihood...
print(joint_likelihood)

# use this in above cased code...
# compressing the joint likehood calculation without an if expression...
# applies for-loop...
for p in patient_data:
    
# returns if statement...         
        joint_likelihood *= logistic_function(p.x) ** p.y * \
                                         (1.0 - logistic_function(p.x)) ** (1.0 - p.y)

# using logrithemic addition...
# value for joint_likelihood...
joint_likelihood = 0.0

# applies for-loop...
for p in patient_data:
    
# returns if statement...         
        joint_likelihood += math.log(logistic_function(p.x) ** p.y * \
                                         (1.0 - logistic_function(p.x)) ** (1.0 - p.y))

# define joint_likelihood is equal to the math.exp(joint_likelihood)...
joint_likelihood = math.exp(joint_likelihood)