# the logistic function in python for on e independent variable...
# importing math
import math as math

# creating def function for predict probability...
def predict_probability(x, b0, b1):
    
# formulate for predict probability...    
    p = 1.0 / (1.0 + math.exp(-(b0 + b1 * x)))
    
# returns value of p...    
    return p
    
# using sympy to plot a logistic function...
# importing symbols and exp from sympy...
from sympy import symbols, exp

# importing plot from.sympy.plotting...
from sympy.plotting import plot

# define b0, b1, x as symbols...
b0, b1, x = symbols('b0 b1 x')

# formula for logistic function...
p = 1 / (1 + exp(-(b0 + b1 * x)))

# substitute value of b0 as p...
p = p.subs(b0, -2.823)

# substitute value of b1 as p...
p = p.subs(b1, 0.620)

# print the function...
print(p)

# plot logistic function...
plot(p)                                